### ISSUE TITLE
No native build was found for platform=linux arch=x64 runtime=node abi=93 uv=1 libc=glibc node=16.13.1

### ISSUE THREAD

**Issue by FDiskas** [Timo972/altv-updater-js#2]
Windows 10
WSL 
```
npx altv-srv --help
```
Got error:
```
***/node_modules/node-gyp-build/index.js:59
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=linux arch=x64 runtime=node abi=93 uv=1 libc=glibc node=16.13.1      
    loaded from: ***/node_modules/altv-srv/node_modules/cfg-reader

    at Function.load.path (***/node_modules/node-gyp-build/index.js:59:9)
    at load (***/node_modules/node-gyp-build/index.js:21:30)
    at Object.<anonymous> (***/node_modules/altv-srv/node_modules/cfg-reader/index.cjs:5:54)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (***/node_modules/altv-srv/dist/helpers/scaffold.helpers.js:4:22)
```

```
  System:
    OS: Linux (wsl) 4.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 8.54 GB / 15.89 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.10 - /c/Program Files/nodejs/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
```

**Comment by FDiskas** [comment]
Can it be related to `cfg-reader` package?
```
Error: No native build was found for platform=linux arch=x64 runtime=node abi=93 uv=1 libc=glibc node=16.13.1      
    loaded from: ***/node_modules/altv-srv/node_modules/cfg-reader
...
```

**Comment by Timo972** [comment]
> Can it be related to `cfg-reader` package?
> 
> ```
> Error: No native build was found for platform=linux arch=x64 runtime=node abi=93 uv=1 libc=glibc node=16.13.1      
>     loaded from: ***/node_modules/altv-srv/node_modules/cfg-reader
> ...
> ```

I guess you are right. Will look into this.

**Comment by Timo972** [comment]
are you able to test the new version on master branch? should be fixed there.
